version: '3.1'

services:

  emscripten:
    build:
      context: ./ubuntu
    image: emscripten-ubuntu:1.0
    ports:
      - 222:22
    environment:
      - ROOT_PASSWORD=test
    volumes:
      - ../:/data